// Generated by scripts/build-config.js — не редактировать вручную.
window.FIREBASE_CONFIG = {
  "apiKey": "AIzaSyD7XKtwUZZYGOUk1Pvmddb5iYsU-eyMRYI",
  "authDomain": "words-aday.firebaseapp.com",
  "projectId": "words-aday",
  "storageBucket": "words-aday.firebasestorage.app",
  "messagingSenderId": "588332608409",
  "appId": "1:588332608409:web:ac4aeb28dda9401dadc108"
};
